# These are supported funding model platforms

# These are supported funding model platforms
patreon: Barimehdi
open_collective: # Replace with a single Open Collective username
ko_fi: barimehdi77
liberapay: Barimehdi77
issuehunt: barimehdi77
custom: 
      - "buymeacoffee.com/barimehdi77"
      - "https://paypal.me/barimehdi77?"
